# Generated by Django 4.2.14 on 2026-07-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invent', '0001_initial'),
        ('basedata', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organ', '0001_initial'),
        ('selfhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.workorder', verbose_name='work order'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='po',
            field=models.ForeignKey(blank=True, limit_choices_to={'entry_status': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.material', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.measure', verbose_name='measure'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='inoutdetail',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.material', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='inoutdetail',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.measure', verbose_name='measure'),
        ),
        migrations.AddField(
            model_name='inoutdetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='initialinventory',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='initialinventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.warereturn'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='out_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.outitem', verbose_name='out item'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.inventory', verbose_name='inventory material'),
        ),
        migrations.AddField(
            model_name='outitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.stockout'),
        ),
        migrations.AddField(
            model_name='inititem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.initialinventory'),
        ),
        migrations.AddField(
            model_name='initem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.stockin'),
        ),
        migrations.AddField(
            model_name='initem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.poitem', verbose_name='po item'),
        ),
        migrations.AddField(
            model_name='adjustitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.inventory', verbose_name='inventory material'),
        ),
        migrations.AddField(
            model_name='adjustitem',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.wareadjust'),
        ),
    ]
