# Generated by Django 4.2.14 on 2026-07-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
        ('purchase', '0001_initial'),
        ('organ', '0001_initial'),
        ('selfhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='woitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.woitem', verbose_name='wo item'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.bankaccount', verbose_name='bank account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.partner', verbose_name='partner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.partner', verbose_name='partner'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder', verbose_name='purchase order'),
        ),
    ]
