# Generated by Django 4.2.14 on 2026-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JackyunSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(default='sale_order', max_length=40, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('running', '进行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='查询开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='查询结束时间')),
                ('fetched', models.IntegerField(default=0, verbose_name='拉取条数')),
                ('created', models.IntegerField(default=0, verbose_name='新建条数')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过条数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败条数')),
                ('message', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='明细 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '吉客云同步日志',
                'verbose_name_plural': '吉客云同步日志',
                'ordering': ['-id'],
            },
        ),
    ]
